services:
  main-service:
    container_name: 'main-service'
    build: .
    ports:
      - 3354:3354
    env_file: '.env'
    volumes:
      - .:/usr/app
    networks:
      - app-tier
    depends_on:
      - main-db

  main-db:
    image: postgres:12.4-alpine
    container_name: 'main-db'
    restart: always
    ports:
      - 5432:5432
    env_file: '.env'
    networks:
      - app-tier
    volumes:
      - pgdata:/data/postgres

  ollama-service:
    image: ollama/ollama
    container_name: 'ollama'
    pull_policy: always
    tty: true
    env_file: '.env'
    ports:
      - 9745:11434
    networks:
      - app-tier
    volumes:
      - ollama:/root/.ollama

networks:
  app-tier:
    driver: bridge

volumes:
  ollama:
    driver: local
  pgdata:
    driver: local
