services:
  main-service:
    ports:
      - 3354:3354
    env_file: '.env.local'
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app

  main-db:
    ports:
      - 5436:5432
    env_file: '.env.local'

  ollama-service:
    env_file: '.env.local'

  pgadmin:
    image: dpage/pgadmin4:6.15
    env_file: '.env.local'
    ports:
      - '9825:80'
    depends_on:
      - main-db
    networks:
      - app-tier
    volumes:
      - ./pgadmin:/pgadmin

volumes:
  postgres_data_sc: {}
